# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions and provides a first line of defense
# against bad commits.

name: Build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21] # Current Java LTS & minimum supported by Minecraft
        # Run on both Linux and Windows
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest Java on one OS
        uses: actions/upload-artifact@main
        with:
          name: Artifacts-pojav
          path: build/libs/
